### ISSUE TITLE
cli: Add mesh parameters to the configuration file

### ISSUE THREAD

**Issue by romac** [circlefin/malachite#289]
Let's add these GossipSub mesh parameters under `[consensus.p2p]`:

```toml
# Target number of peers for the mesh network (D in the spec,
mesh_n = 6

# Maximum number of peers in mesh network before removing some (D_high in the GossipSub spec)
mesh_n_high = 12

# Minimum number of peers in mesh network before adding more (D_lo in the spec)
mesh_n_low = 4

# Minimum number of outbound peers in the mesh network before adding more (D_out in the spec).
# This value must be smaller or equal than `mesh_n / 2` and smaller than `mesh_n_low`.
mesh_outbound_min = 2
```

The latter one could perhaps be computed from `mesh_n` and `mesh_n_low`?
